

VARIABLE_REGEX = r'([a-zA-Z]\w*)'
NUMBER_RE = r'(\d+(?:\.\d+)?)'
SPECIAL_ARGUMENT_RE = fr'([$@]{VARIABLE_REGEX}*)'
ARGUMENT_RE = fr'({NUMBER_RE}|{SPECIAL_ARGUMENT_RE}|{VARIABLE_REGEX})'
ARGUMENT_WITH_COMMA_RE = fr'({ARGUMENT_RE}, *)'
FUNCTION_REGEX = fr'({VARIABLE_REGEX}\({ARGUMENT_WITH_COMMA_RE}*{ARGUMENT_RE}?\))'
